# Generated by Django 5.1.1 on 2024-10-05 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=250)),
                ('weather', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='trip_images/')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
