# Generated by Django 5.1.1 on 2024-10-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='image',
            new_name='Trip_img',
        ),
    ]
