# Generated by Django 5.1.1 on 2024-10-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0002_rename_image_trip_trip_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='weather',
            field=models.CharField(max_length=200),
        ),
    ]
